# Ficheiro de configuracao, porfavor nao modifique-o

title: Zambeze
description: O Paraiso Misterioso
email: info@paraisomisterioso.com
url: https://paraisomisterioso.com

plugins_dir: _plugins
collections_dir: servicos 

plugins:
  - 'jekyll-email-protect' 
  - 'jekyll-paginate-v2'
  - 'jekyll-seo-tag'
  - 'jekyll-sitemap'
  - 'jekyll-analytics'

collections:
  hotel:
  galeria:
  diversos:
  pastelaria:
  restaurante:

# Build settings
markdown: kramdown
permalink: pretty

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: ""       # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

exclude:
  - bower_components

sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/header/zpm-web.png

pagination:
  enabled: true
  per_page: 9
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

color: "#009ed5"