title: Zambeze
email: info@zambeze.co
description: O Paraiso Misterioso
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zambeze.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: imaz_3g
github_username:  zinenda

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autolink_email
  - jekyll-email-protect

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/
  - bower_components/
  - admin/index.js
  - webpack.config.js
  - package.json
  - README.md
  - bower.json
  - yarn.lock

sass:
  sass_dir: _sass
  style: compressed
