backend:
  name: git-gateway
  branch:
    - master
    - hotel-theme
  accept_roles:
    - admin

media_folder: "assets/img/uploads"

collections:
  - name: "slider"
    label: "Slider"
    folder: "servicos/_slider"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}

  - name: "pacotes"
    label: "Pacotes"
    folder: "servicos/_pacotes"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Preço", name: "price", widget: "number"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

  - name: "restaurante"
    label: "Restaurante"
    folder: "servicos/_restaurante"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Preço minimo", name: "price", widget: "number", required: "false"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

  - name: "pastelaria"
    label: "Pastelaria"
    folder: "servicos/_pastelaria"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Preço minimo", name: "price", widget: "number", required: "false"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

  - name: "hotel"
    label: "Hotel"
    folder: "servicos/_hotel"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Preço minimo", name: "price", widget: "number", required: "false"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

  - name: "diversos"
    label: "Diversos"
    folder: "servicos/_diversos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Preço minimo", name: "price", widget: "number", required: "false"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

  - name: "explore"
    label: "Explore"
    folder: "servicos/_explore"
    create: true
    widget: "list"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagens", name: "images", widget: "image"}