backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master 

media_folder: "assets/img/uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Youtube Trailer", name: "trailer", widget: "string"}
      - label: "Categorias"
        name: "category"
        widget: "select"
        options: ["Acção", "Animação", "Drama", "Ficção", "Suspence", "Terror"]
      - label: "Autor"
        name: "author"
        widget: "select"
        options: ["Zinenda", "Magagula", "Aniz"]
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Corpo", name: "body", widget: "markdown"}